---
- name: Ensure grafana.ini is present
  template:
    src: 'grafana.ini'
    dest: /etc/grafana/grafana.ini
  notify:
    - restart_grafana
  tags: configure

- name: Ensure datasource config is present
  copy:
    src: 'prom-datasource.yml'
    dest: /etc/grafana/provisioning/dashboards/prom.yml
  notify:
    - restart_grafana
  tags: configure

- name: Create dir for dashboards
  file:
    path: /var/lib/grafana/dashboards
    state: directory
  tags: configure

- name: Ensure dashboard config is present
  copy:
    src: 'default-dashboard.yml'
    dest: /etc/grafana/provisioning/dashboards/default.yml
  notify:
    - restart_grafana
  tags: configure

- name: Ensure dashboard files are present
  copy:
    src: '{{ item }}'
    dest: "/var/lib/grafana/dashboards/{{ item }}"
  loop:
    - 'dashboard_open5gs.json'
    - 'dashboard_hosts.json'
  notify:
    - restart_grafana
  tags: configure
