---
- name: Ensure grafana is installed on Ubuntu
  apt:
    deb: 'https://dl.grafana.com/oss/release/grafana_{{ grafana_version }}_amd64.deb'
    state: present

- name: Ensure docker deps are present
  pip:
    name: "{{ item }}"
    state: present
  loop:
    - docker
    - six

