---
- name: Ensure dns address is set inside systemd resolved config
  lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: '^.*DNS='
    line: "DNS= {{ dns_address }}"
    state: present
  notify: restart_systemd_resolved

- name: Set domains inside systemd resolved config
  lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: '^#Domains='
    line: "Domains=~."
    state: present
  notify: restart_systemd_resolved

- name: Check if /etc/resolv.conf is symlink
  stat:
    path: /etc/resolv.conf
  register: resolv_conf_stat

- name: Remove /etc/resolv.conf if it's not a symlink or wrong target
  file:
    path: /etc/resolv.conf
    state: absent
  when: (not resolv_conf_stat.stat.islnk ) or ( resolv_conf_stat.stat.islnk and resolv_conf_stat.stat.lnk_target != resolve_config_link_path)

- name: Create symlink /etc/resolv.conf to /run/systemd/resolve/resolv.conf
  file:
    src: "{{resolve_config_link_path}}"
    dest: /etc/resolv.conf
    state: link
    owner: root
    group: root
  notify: restart_systemd_resolved
  when: (not resolv_conf_stat.stat.islnk) or (resolv_conf_stat.stat.islnk and resolv_conf_stat.stat.lnk_target != resolve_config_link_path)

- meta: flush_handlers

