---
- name: Create config dir
  ansible.builtin.file:
    path: /etc/ueransim
    state: directory

- name: Copy systemd units
  ansible.builtin.template:
    dest: "/lib/systemd/system/nr-gnb.service"
    src: "nr-gnb.service"
  notify: daemon_reload

- name: Copy gnb config
  ansible.builtin.template:
    src: gnb.yaml
    dest: '/etc/ueransim/gnb.yaml'
  notify:
    - restart_gnb

- name: Make sure systemd is started and enables
  ansible.builtin.systemd:
    name: "nr-gnb.service"
    state: started
    enabled: yes
