---
- name: Stop 5g control plane services if user plane
  ansible.builtin.systemd:
    name: "open5gs-{{ item }}d"
    state: stopped
    enabled: no
  loop: '{{ services_5g_control_plane }}'
  tags: configure

- name: Copy configs
  ansible.builtin.template:
    src: "configs/{{ item }}.yaml"
    dest: "/etc/open5gs/{{ item }}.yaml"
  loop: '{{ services_5g_user_plane }}'
  notify: 'restart {{ item }}'
  tags: configure

- name: Copy systemd units
  ansible.builtin.template:
    src: "services/open5gs-{{ item }}d.service"
    dest: "/lib/systemd/system/open5gs-{{ item }}d.service"
  loop: '{{ services_5g_user_plane }}'
  notify: daemon_reload
  tags: configure

- name: Copy network tunnel interface config
  ansible.builtin.template:
    src: network-interface/{{ item }}
    dest: /etc/systemd/network/{{ item }}
  loop:
    - "99-open5gs.netdev"
    - "99-open5gs.network"
  notify:
    - daemon_reload
    - restart systemd-networkd
  tags: configure

- name: Make sure services are started and enable
  ansible.builtin.systemd:
    name: "open5gs-{{ item }}d"
    state: started
    enabled: yes
  loop: '{{ services_5g_user_plane }}'
  tags: configure
