---

- name: copy consul service
  template:
    src: consul.service
    dest: '/etc/systemd/system/consul.service'
  tags: configure

- name: copy consul config
  template:
    src: 'consul-{{ consul_host_role }}.hcl'
    dest: '{{ consul_config_dir }}/consul.hcl'
  notify: restart_consul
  tags: configure

- name: add CAP_NET_BIND_SERVICE
  capabilities:
    path: '{{ consul_bin_dir }}/consul'
    capability: CAP_NET_BIND_SERVICE=+eip
    state: present
  tags: configure