---
- name: install unzip
  package:
    name: unzip

- name: install consul
  unarchive:
    src: '{{ consul_bin_url }}'
    remote_src: yes
    dest: '{{ consul_bin_dir }}'
    owner: root
    group: root
  notify: restart_consul

- name: add consul group
  group:
    name: consul
    system: yes

- name: add consul user
  user:
    name: consul
    group: consul
    home: '{{ consul_config_dir }}'
    shell: '/bin/false'

- name: create /opt/consul
  file:
    path: '{{ consul_data_dir }}'
    state: directory
    owner: consul
    group: consul
