---

- hosts:
    - open5gs-core
    - open5gs-user-plane
  become: yes
  serial: 20
  vars:
    #################################################
    ## VARS MAINLY SET IN GROUP_VARS AND HOST_VARS ##
    #################################################

    ## COMMON VARS FOR CORE AND UPF
    network_enable_ip_forwarding: yes

    upf_subnets:
      open5gs-upf-waw-1:
        - addr: 10.45.0.1/16
          subnet: 10.45.0.0/16
          dnn: internet-waw
          dev: ogstun
      open5gs-upf-bhs-1:
        - addr: 10.46.0.1/16
          subnet: 10.46.0.0/16
          dnn: internet-bhs
          dev: ogstun
      open5gs-upf-de-1:
        - addr: 10.47.0.1/16
          subnet: 10.47.0.0/16
          dnn: internet-de
          dev: ogstun

    upf_pfcp_address:
      open5gs-upf-waw-1: 10.30.0.13
      open5gs-upf-bhs-1: 10.30.4.14
      open5gs-upf-de-1:  10.30.1.40

  vars_files:
    - ../vars/secrets.yml

  roles:
    - {role: piotmni.initial_setup, tags: initial_setup}
    - {role: piotmni.network_ubuntu, tags: [network]}
    - {role: piotmni.firewall_ubuntu, tags: [network, firewall]}
    - {role: piotmni.hosts, tags: [network, hosts]}
    - {role: piotmni.resolve, tags: [network, resolve]}
    - {role: piotmni.wireguard, tags: wireguard}
    - {role: piotmni.nodejs, tags: [nodejs], when: "'open5gs-core' in group_names"}
    - {role: piotmni.open5gs, tags: open5gs }
    - {role: piotmni.telegraf, tags: telegraf}

