---
- hosts: localhost
  become: yes
  serial: 1
  vars:
    inventory_hostname: "lb-de-1"
    dc: "de1"
    network_enable_ip_forwarding: yes
    firewall_ports:
      - { to_port: 80, zone: public }
      - { to_port: 80, zone: home }
      - { to_port: 443, zone: public }
      - { to_port: 443, zone: home }
      - { to_port: 1081, zone: home } # telegraf
      - { interface: docker0 }

  vars_files:
    - ../vars/users.yml
    - ../vars/secrets.yml
    - ../vars/lb-packer.yml

  roles:
    - {role: piotmni.common, tags: common}
    - {role: piotmni.initial_setup, tags: initial_setup}
    - {role: piotmni.haproxy, tags: [haproxy]}
    - {role: piotmni.telegraf, tags: telegraf}
