---
# tasks file for free5gc
- name: free5gc | gather facts
  ansible.builtin.package_facts:
    manager: auto

- include_tasks: install.yml

- include_tasks: control_plane.yml
  when: control_plane_node is true

- include_tasks: user_plane.yml
  when: user_plane_node is true
