---
- name: free5gc-webconsole | check if already installed
  stat:
    path: /usr/bin/free5gc-webconsole
  register: webconsole_bin

- block:
    - name: free5gc-webconsole | make
      make:
        chdir: /opt/free5gc/
        target: "webconsole"
      environment:
        GOPATH: /opt/gopath
        GOROOT: /usr/local/go
        PATH: /sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin:/usr/local/go/bin

    - name: free5gc-webconsole | copy binaries
      ansible.builtin.copy:
        mode: 0755
        remote_src: yes
        src: /opt/free5gc/webconsole/bin/webconsole
        dest: /usr/bin/free5gc-webconsole
  when: webconsole_bin.stat.exists == False

- name: free5gc-webconsole | copy public
  ansible.builtin.copy:
    remote_src: yes
    src:  /opt/free5gc/webconsole/public/
    dest: /etc/free5gc/public

- name: free5gc-webconsole | copy configs
  ansible.builtin.template:
    dest: /etc/free5gc/webconsole.yaml
    src: configs/webconsole.yaml
  notify: restart webconsole

- name: free5gc-webconsole | copy systemd unit
  ansible.builtin.template:
    dest: /lib/systemd/system/free5gc-webconsoled.service
    src: services/free5gc-webconsoled.service
  notify: daemon_reload

- name: free5gc-webconsole | ensure webconsole is started and enabled
  ansible.builtin.systemd:
    name: free5gc-webconsoled
    state: started
    enabled: yes
