{
 "title": "host dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "query": { "query": "up" } },
   {
    "name": "node",
    "query": {
     "query": "up{job=~\"$job\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "cpu_usage_guest{cpu=\"cpu-total\", instance=\"$node\", job=\"$job\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "cpu_usage_guest_nice{cpu=\"cpu-total\", instance=\"$node\", job=\"$job\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "cpu_usage_irq{cpu=\"cpu-total\", instance=\"$node\", job=\"$job\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "cpu_usage_nice{cpu=\"cpu-total\", instance=\"$node\", job=\"$job\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "cpu_usage_softirq{cpu=\"cpu-total\", instance=\"$node\", job=\"$job\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "cpu_usage_system{cpu=\"cpu-total\", instance=\"$node\", job=\"$job\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "cpu_usage_user{cpu=\"cpu-total\", instance=\"$node\", job=\"$job\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "cpu_usage_iowait{cpu=\"cpu-total\", instance=\"$node\", job=\"$job\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "cpu_usage_idle{cpu=\"cpu-total\", instance=\"$node\", job=\"$job\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "mem_total{instance=\"$node\", job=\"$job\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "mem_buffered{instance=\"$node\", job=\"$job\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "mem_cached{instance=\"$node\", job=\"$job\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "mem_active{instance=\"$node\", job=\"$job\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "mem_mapped{instance=\"$node\", job=\"$job\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "mem_free{instance=\"$node\", job=\"$job\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "disk usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "disk_used_percent{instance=\"$node\", job=\"$job\", path!~\"/var/lib/docker/overlay2/.*\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "available memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 9 },
   "targets": [
    {
     "expr": "mem_available_percent{job=\"$job\", instance=\"$node\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  }
 ]
}