{
 "title": "Open5gs",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "amf sessions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "amf_session{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "GNBs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 10, "y": 0 },
   "targets": [
    { "expr": "gnb", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "active ue session per upf",
   "type": "stat",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fivegs_upffunction_upf_sessionnbr",
     "legendFormat": "{{host}}"
    }
   ]
  }
 ]
}