---
- name: daemon_reload
  systemd:
    daemon_reload: yes

- name: prometheus_restart
  systemd:
    name: prometheus
    state: restarted

- name: prometheus_reload
  systemd:
    name: prometheus
    state: reloaded
